### ISSUE TITLE
Rename shim-client to shim-proto

### ISSUE THREAD

**Issue by jiangliu** [containerd/rust-extensions#1]
The shim-client provides message and trait definitions for both server and client, so it would be great to rename it as shim-proto.

**Comment by mxpv** [comment]
You mean directory name or crate name?
Crate itself named `containerd-shim-client` (I used `containerd-` prefix everywhere for clarity that this is relevant for containerd).
I don't mind having `containerd-shim-proto`, the only cons I see is that this crate is already published on crates.io, so renaming might be a bit confusing to users which one is correct to use.

**Comment by jiangliu** [comment]
> You mean directory name or crate name? Crate itself named `containerd-shim-client` (I used `containerd-` prefix everywhere for clarity that this is relevant for containerd). I don't mind having `containerd-shim-proto`, the only cons I see is that this crate is already published on crates.io, so renaming might be a bit confusing to users which one is correct to use.

I mean to rename the crate name. It's great to share "containerd-" prefix for all crates from the rust-extensions project. I prefer "containerd-shim-proto" over "containerd-shim-client" because 
1) it's a library instead of a binary
2) it contains code for both server and client.

But it's true that it may cause some confusions:(

**Comment by jiangliu** [comment]
Seems `cargo yank` may help here:
https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-yank
