### ISSUE TITLE
Failed CI

### ISSUE THREAD

**Issue by utam0k** [containerd/rust-extensions#110]
:wave: Hi, team. Thanks for your effort on this project. I love and use this project.

# Problem

There are two failed cases on the CI.
- `TestTaskUpdate`
  ```text
  === CONT  TestTaskUpdate
      container_linux_test.go:249: Others("Other: set mem limit: unable to write to a control group file caused by: Os { code: 13, kind: PermissionDenied, message: \"Permission denied\" }"): unknown
      container_linux_test.go:258: expected memory limit to be set to 67108864 but received 33554432
  --- FAIL: TestTaskUpdate (0.14s)
  ```

- TestContainerMetrics 
  ```text
  === CONT  TestContainerMetrics
  1160
      container_test.go:1345: not found
  1161
  --- FAIL: TestContainerMetrics (0.23s)
  ```

# Expected behavior

Pass the CI

# How to solve

Should we ignore these test cases once?

**Comment by Burning1020** [comment]
`TestTaskUpdate` and `TestContainerMetrics` have been failed for a long time. They all with regard to some operations in Cgroup I think.
