### ISSUE TITLE
Proposal: Add `--version` flag to print the build info of the binary

### ISSUE THREAD

**Issue by Mossaka** [containerd/rust-extensions#120]
It would be nice to have a --version arg for the shims to be able to determine the build version information.

**Comment by Burning1020** [comment]
I agree. How much information that "--version" or "-version" should provide?
eg: name, version number, git commit id, rust version?

**Comment by Mossaka** [comment]
Hey @Burning1020 , thanks for your quick response! I am thinking about at least to provide information about the cargo version from env var like `env!(CARGO_PKG_VERSION)`. It would be better to include information from `git`, like git commit SHA, last build datetime etc. I am not sure how useful Rust version would be in the binary though. 

Here is an [example](https://github.com/bytecodealliance/wit-bindgen/blob/main/build.rs#L28-L33) of how to get these information from git in build time.

**Comment by Burning1020** [comment]
I see. Would you help commit this PR or I can do it lately (got other work to do now) ?

**Comment by Mossaka** [comment]
Sure I can give it a try. Do you think if it's reasonable to add a new flag to https://github.com/containerd/rust-extensions/blob/main/crates/shim/src/args.rs#L24-L42? 

Also, unrelated to this issue, but what do you think about using [clap](https://docs.rs/clap/latest/clap/) to build the CLI experience of the shim?

**Comment by Burning1020** [comment]
> Sure I can give it a try. Do you think if it's reasonable to add a new flag to https://github.com/containerd/rust-extensions/blob/main/crates/shim/src/args.rs#L24-L42?
> 
Yes, maybe there is no other reasonable places.

> Also, unrelated to this issue, but what do you think about using [clap](https://docs.rs/clap/latest/clap/) to build the CLI experience of the shim?

Clap doesn't support for short flag at present, see here:https://github.com/clap-rs/clap/issues/2468#issuecomment-1330593029, so it can't read the [flags ](https://github.com/containerd/containerd/blob/main/runtime/v2/binary.go#L67)from containerd.
