### ISSUE TITLE
Proposal: remove sync code

### ISSUE THREAD

**Issue by Burning1020** [containerd/rust-extensions#134]
In Rust, synchronous (sync) code is blocking, which means it will wait for a response before continuing with the next task. This can lead to slow performance if there are many synchronous operations.

On the other hand, asynchronous (async) code is non-blocking, which means it can perform other tasks while waiting for a response. This allows for better performance and can be especially useful in network applications where there are many concurrent requests.

Initially, I was hesitant about using async shim because it wasn't very stable in testing. Additionally, the Rust async ecosystem is still evolving and some libraries may not have full support for async yet. However, after doing some research, I found that most mainstream rust crates are now using async crates. If there are any bugs in async shim, we should work on fixing them instead of relying on sync code. 

Therefore, I decide to **stop developing sync code**. If you have any opinion, please leave a comment below. If there are no objections after one month(May 15th), we'll proceed with the plan to remove sync code in the next version.

Before we officially deprecate it, I will still commit PRs to fix some bugs.

/cc @mxpv @jiangliu @abel-von @ytoml @wedsonaf @AkihiroSuda

**Comment by jsturtevant** [comment]
[Runwasi ](https://github.com/containerd/runwasi) is using the sync code today /cc @cpuguy83

**Comment by cpuguy83** [comment]
"sync" code just needs to use threads instead of an async runtime.

I actually do not see how any shim would ever have enough traffic hitting it that using async would make any real difference here.

**Comment by Burning1020** [comment]
Yes, maybe I haven't made it cleaer. We have many funcs written by both sync and async, they have the same function so that we need maintance two codes. Like [async fn notify_topic](https://github.com/containerd/rust-extensions/blob/main/crates/shim/src/asynchronous/monitor.rs#L112) and [fn notify_topic](https://github.com/containerd/rust-extensions/blob/main/crates/shim/src/synchronous/monitor.rs#L107)

What I want to do is to remove funcs both have sync and async, if you want do call async func in sync func, try tokio block_on? https://docs.rs/tokio/latest/tokio/runtime/struct.Runtime.html#method.block_on

**Comment by mxpv** [comment]
@Burning1020 we can start with removing sync code from the `runc-shim` crate to reduce maintenance burden. As for `shim` crate, I'd prefer to keep it slim and implementation agnostic, so we can move monitor stuff up the `runc-shim`, and continue to keep a small portion of sync/async code (like publisher).
