### ISSUE TITLE
Request for a new release of `containerd-shim` crate

### ISSUE THREAD

**Issue by Mossaka** [containerd/rust-extensions#158]
Hi there, 

I am a maintainer from `runwasi` project under the Containerd org. `runwasi` is taking a dependency on the `containerd-shim`crate. I'd like to request for a new release of this crate because it's been a year since the last release and we want to include features like #150 in the new release of `runwasi`'s `containerd-shim-wasm` crate. 🙏🙏

**Comment by mxpv** [comment]
Published 0.4: https://crates.io/crates/containerd-shim
