### ISSUE TITLE
Consolidate shim-proto from runD for kata v3.0

### ISSUE THREAD

**Issue by jiangliu** [containerd/rust-extensions#2]
There's an ongoing efforts to upstream Alibaba's runD for Kata 3.0. There's a similar implementation of shim-client/shim-proto from runD. It would be great to consolidate these two implementations.

**Comment by AkihiroSuda** [comment]
What is runD?

**Comment by fuweid** [comment]
> What is runD? 

runDragonball I think.

**Comment by AkihiroSuda** [comment]
> > What is runD?
> 
> runDragonball I think.

So, what is runDragonball ? 😅
Is there any repo or doc?

**Comment by fuweid** [comment]
> > > What is runD?
> 
> > 
> 
> > runDragonball I think.
> 
> 
> 
> So, what is runDragonball ? 😅
> 
> Is there any repo or doc?

https://medium.com/kata-containers/kata-containers-vptg-community-gathering-new-features-and-a-glimpse-of-kata-3-0-7ba025025e9e 

Section: Integrated Rust Runtime

Less docs are about this, since it is not open source. @AkihiroSuda

**Comment by jiangliu** [comment]
> > > What is runD?
> > 
> > 
> > runDragonball I think.
> 
> So, what is runDragonball ? 😅 Is there any repo or doc?

Let me give some background.
Dragonball is a light-weight microvm written in rust, which is similar to firecracker/cloud hypervisor.
`runD` is a kata-runtime written in rust, which has integrate container runtime(shim-v2) and microvm together.
We are in the process to upstream runD to Kata Containers. Here are some references:
https://github.com/kata-containers/kata-containers/issues/3052
https://github.com/kata-containers/kata-containers/pull/3251/files
