### ISSUE TITLE
Could you release a new version of `containerd_shim`?

### ISSUE THREAD

**Issue by justxuewei** [containerd/rust-extensions#226]
Hi, there.

I encountered an issue with the protobuf dependency. The details are as follows:

- Kata Containers' runtime-rs has a dependency on `protobuf v3.2.0` and `ttrpc v0.7.1`.
- Kata Containers has a dependency on `containerd-shim-protos v0.3.0`, which correctly depends on `protobuf v3.2.0` and `ttrpc v0.7.1`.
- Kata Containers also has a dependency on `containerd-shim v0.3.0`. However, it has a dependency on `containerd-shim-protos v0.2.0`, which in turn depends on `protobuf v2.28` and `ttrpc v0.6`. See [containerd-shim v0.3.0](https://crates.io/crates/containerd-shim/0.3.0/dependencies) and [containerd-shim-protos v0.2.0](https://crates.io/crates/containerd-shim-protos/0.2.0/dependencies).

A feasible solution is to release a new version of `containerd_shim` with the correct dependency:

- `containerd-shim-protos v0.3.0`
- `protobuf v3.2.0`
- `ttrpc v0.7.1`

Wdyt? /cc @mxpv @fuweid @jiangliu

**Comment by justxuewei** [comment]
@mxpv Thank you a lot!

**Comment by justxuewei** [comment]
Hi, @mxpv! Could you help release a new version this week?

**Comment by mxpv** [comment]
@justxuewei hey, apologies for delay. Now that I have more time to take a closer look.
I'm slightly confused with this. 

> Kata Containers also has a dependency on containerd-shim **v0.3.0**. However, it has a dependency on containerd-shim-protos v0.2.0, which in turn depends on protobuf v2.28 and ttrpc v0.6

Latest `containerd-shim` crate version is [v0.6.0](https://crates.io/crates/containerd-shim), which depends on containerd-shim-protos `v0.6.0`, which uses fresh versions of ttrpc and protobuf. Have you tried it?

**Comment by justxuewei** [comment]
Hi @mxpv. Happy new year! Hope you have a nice holiday.

I decided to upgrade kata-containers' `ttrpc` and `containerd-shim` to the latest version. Thanks for your advice.
