### ISSUE TITLE
Is there a plan for  for registering and reporting cgroup OOM events in Rust shim?

### ISSUE THREAD

**Issue by aa624545345** [containerd/rust-extensions#227]
Go shim uses memory.oom_control and cgroup.event_control to register and report OOM (Out of Memory) events in the cgroup. Do you now have any plans for this aspect in Rust shim?

**Comment by Burning1020** [comment]
Sounds good to me. I can handle this in this week.

**Comment by Burning1020** [comment]
@aa624545345 Are you using shim with async feature?

**Comment by aa624545345** [comment]
Not yet. I just tested the async version and found this lack. I commit a pr for this lack in #229

**Comment by Burning1020** [comment]
> Not yet. I just tested the async version and found this lack. I commit a pr for this lack in #229

Oh, thank you.
