### ISSUE TITLE
Will the rust-extensions support Windows?

### ISSUE THREAD

**Issue by jiangliu** [containerd/rust-extensions#4]
Seems currently implementation supports UNIX-like OSs only, is there any plan for Windows or it's ok to focus on Unix-like OSs?

**Comment by mxpv** [comment]
I don't have windows environment, so I haven't tried it.
But it would be good to support all platforms though.
I think a good starting point would be to get [ttrpc-rust](https://github.com/containerd/ttrpc-rust) running on windows CI, to make sure nothing is broken.
Rust extensions should be straightforward to port

**Comment by jiangliu** [comment]
It would be great to support Windows, but it does need some efforts. So how about marking it as an TODO?

**Comment by mxpv** [comment]
Sure, let's keep this open

**Comment by jsturtevant** [comment]
was able to get most of the shim related code to build using https://github.com/containerd/ttrpc-rust/issues/132 with a few tweaks
