### ISSUE TITLE
Couldn't get any output from runc commands

### ISSUE THREAD

**Issue by Burning1020** [containerd/rust-extensions#44]
The stdout/stderr of `runc` command is deliverd by a "**pipe**" by default here: 
https://github.com/pwFoo/rust-runc/blob/master/src/lib.rs#L509
```rust
        let process = Command::new(&self.command)
            .args(&args.clone())
            .stdin(Stdio::null())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
```
which is different from our "**inherit**" way: https://github.com/containerd/rust-extensions/blob/main/crates/runc/src/lib.rs#L121
```rust
        // Default to inherited stdio, and they may be override by command options.
        cmd.stdin(Stdio::null())
            .stdout(Stdio::inherit())
            .stderr(Stdio::inherit());
```
 
Although it can be override by command options as @jiangliu said, these optios also need a `pub io: Option<Arc<dyn Io>>` field member, otherwise, the output may passed to partent command. 

Take shim as an example, it will redirect its log message into a fifo, leaving stdio to `/dev/null`. So we can't get error message anymore.

I perfer using a pipe rather than inherited to avoid adding member in every options.
cc @mxpv @jiangliu

**Comment by jiangliu** [comment]
We have introduced `PipedStdIo` to help the situation, https://github.com/containerd/rust-extensions/blob/main/crates/runc/src/io.rs#L250.
Will it help here?

**Comment by Burning1020** [comment]
> We have introduced `PipedStdIo` to help the situation, https://github.com/containerd/rust-extensions/blob/main/crates/runc/src/io.rs#L250. Will it help here?

`PipedStdIo` helps. My point is in order to override it, every command options need a `pub io: Option<Arc<dyn Io>>` field member.

**Comment by jiangliu** [comment]
As we have provided both `InheritedStdIo` and `PipedStdIo`, it would be reasonable to make the most popular one as the default. And it's easy to override it when the default value doesn't work.

**Comment by Burning1020** [comment]
As you see in https://github.com/containerd/rust-extensions/pull/37#issuecomment-1053704381, stdout and stderr are empty in the returned error message.
```bash
2022-02-27T22:25:36.2249644Z     container_test.go:716: expected error "not found" but received "Others(\"Other: unknown error after kill: runc command failed: status=exit status: 1, stdout=\\\"\\\", stderr=\\\"\\\"\"): unknown"
```
The reason may be that they are deliverd to shim stdio and redirected to `/dev/null`.

**Comment by Burning1020** [comment]
1. `Inherited StdIo` will pass the stdout/stderr to parent process stdio.
2. `Piped StdIo` will pass them to parent process itself.

If first one is by default, we need add a io member in every command optios so as to deliver output to shim process itself instead of its stdio.
