### ISSUE TITLE
hello-world fail

### ISSUE THREAD

**Issue by QuarkContainer** [containerd/rust-extensions#53]
I tried to run the shim as below.

sudo ctr run --rm --runtime io.containerd.skeleton.v1 -t docker.io/library/hello-world:latest hello --debug

And got failure as below.

ctr: failed to create shim: /containerd.task.v2.Task/Create is not supported: not found

I tried to debug it but don't know the log location. Can you please share log location?

**Comment by abel-von** [comment]
the skeleton is not a full runc shim, you should use containerd-shim-runc-v2 in the target path, it is a binary from crates/runc-shim project。

**Comment by jsturtevant** [comment]
I ran into this as well when following the directions at https://github.com/containerd/rust-extensions/tree/main/crates/shim#how-to-use-with-containerd.  Should that readme be updated? The "manual" approach did work for me.
