### ISSUE TITLE
Document comptable Containerd versions in README.md

### ISSUE THREAD

**Issue by jiangliu** [containerd/rust-extensions#6]
Containerd is still evolving quickly, interfaces and behaviors may change between Cotnainerd versions. It would be great to document compatible Containerd versions for each version of rust crates in the README.md.

**Comment by lifupan** [comment]
Yeah，it's better to release the extensions version the same to the latest compatible containerd version, thus the extension users can easily know that their programs compatible with which containerd version.

**Comment by mxpv** [comment]
We usually don't do changes that break compatibility but rather deprecate things.
Shim runtime v2 expected to work with newer versions of containerd.
(we have an issue to add CI tests to track binary compatibility - https://github.com/containerd/containerd/issues/3757).

So I'm not sure there is strong need to keep up with containerd releases.
I'd rather do (somewhere on my list) integration tests for the rust extensions. I believe we can do a matrix on containerd versions similarly to how it's done in [nerdctl](https://github.com/containerd/nerdctl) (example https://github.com/containerd/nerdctl/runs/4518724866) to make sure no things broken.

**Comment by jiangliu** [comment]
It's a great idea to setup CI tests to ensure compatibility between shim and Containerd. 
The goal is to guarantee  compatibility:)
