### ISSUE TITLE
runc-shim failed

### ISSUE THREAD

**Issue by q741242673** [containerd/rust-extensions#71]
tried to run the shim as below.

sudo ctr run --rm --runtime io.containerd.runc.v2-rs -t docker.io/library/hello-world:latest hello 

And got failure as below.

unix:///run/containerd/e2575a053069a275.sock: connect: invalid argument: unknown

I tried to debug and found that ctr seem  failed  to connect address the shim created

**Comment by Burning1020** [comment]
hi, could you mind to provide more information, like containerd related log? thanks!

**Comment by mxpv** [comment]
I'm going to close this one. Please get back if you still experience this problem.
